apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot-app
  namespace: default
  labels:
    app: heybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot
  template:
    metadata:
      labels:
        app: heybot
    spec:
      serviceAccountName: heybot-sa
      containers:
        - name: heybot
          image: ghcr.io/mohamadsallakhou/heybot-with-trivy-output:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: heybot-config
            - secretRef:
                name: heybot-secrets
          ports:
            - name: http
              containerPort: 7861
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7861
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 7861
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      imagePullSecrets:
        - name: ghcr-secret
