# deployment.yaml  (heybot-app)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heybot-app
  namespace: default
  labels:
    app: heybot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heybot
  template:
    metadata:
      labels:
        app: heybot
    spec:
      serviceAccountName: heybot-sa
      containers:
        - name: heybot
          image: ghcr.io/mohamadsallakhou/heybot-with-trivy-output:latest
          imagePullPolicy: Always
          # Umgebungsvariablen aus ConfigMap & Secret
          envFrom:
            - configMapRef:
                name: heybot-config     # HUMOR_MODEL, OTHER_SETTING :contentReference[oaicite:2]{index=2}:contentReference[oaicite:3]{index=3}
            - secretRef:
                name: heybot-secrets    # OLLAMA_API_URL, DISCORD_WEBHOOK_URL :contentReference[oaicite:4]{index=4}:contentReference[oaicite:5]{index=5}
          # Explizit Ollama als Modell-Backend
          env:
            - name: MODEL_PROVIDER
              value: "ollama"
            - name: OLLAMA_API_URL
              valueFrom:
                secretKeyRef:
                  name: heybot-secrets
                  key: OLLAMA_API_URL
          ports:
            - name: http
              containerPort: 7861
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7861
            initialDelaySeconds: 10
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 7861
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
      imagePullSecrets:
        - name: ghcr-secret
