apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook
  namespace: default
type: Opaque
stringData:
  url: "https://discord.com/api/webhooks/1369335970742276166/1KiWkWW1nDAi6c54YOkL8FqJs9n5ifu0xRHyNwQFFBo-ORWblfENCpJpEyIstdGvPzb3"
