apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - deployment.yaml             # heybot-app
  - service.yaml                # heybot-service
  - ollama-deployment.yaml
  - ollama-service.yaml
  - pvc.yaml                    # ollama-models-pvc
  - trivy-scan-job.yaml         # falls du den Trivy-Job ins Git gelegt hast
  - dynamic-risk-analyzer.yaml  # wenn dein „dynamic-risk-analyzer“ Deployment + Service in einer Datei
  # oder einzeln:
  #- dynamic-risk-analyzer-deployment.yaml
  #- dynamic-risk-analyzer-service.yaml
