# ollama-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ollama-svc
  namespace: default
  labels:
    app: ollama
spec:
  selector:
    app: ollama
  ports:
    - name: api
      protocol: TCP
      port: 11434
      targetPort: 11434
  type: ClusterIP
