apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heybot-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: heybot-sa
    namespace: default
roleRef:
  kind: Role
  name: heybot-role
  apiGroup: rbac.authorization.k8s.io
