name: Docker Image Scan

on:
  push:
    branches: [ main ]

jobs:
  trivy_scan:
    runs-on: ubuntu-latest

    steps:
      # 1) Code auschecken
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Buildx und QEMU für Multi-Arch aktivieren (optional)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3) Einloggen in GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # 4) Docker-Image bauen & pushen
      - name: Build & push heybot:latest
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/heybot:latest

      # 5) Trivy-Scan
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@v0.9.2
        with:
          image-ref: ghcr.io/${{ github.actor }}/heybot:latest
          format: json
          output: trivy_output.json

      # 6) neues Image mit Scan-Report bauen & pushen
      - name: Build & push heybot-with-trivy-output:latest
        run: |
          docker build \
            -f Dockerfile.trivy-analysis \
            -t ghcr.io/${{ github.actor }}/heybot-with-trivy-output:latest \
            .
          docker push ghcr.io/${{ github.actor }}/heybot-with-trivy-output:latest
